### ISSUE TITLE
Add INIT Script

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#16]
See https://github.com/spajus/hubot-example/blob/master/misc/hubot.init.d.centos.sh.

**Comment by greenpotatochip** [comment]
Does hubot only live on mon.door43.org?

**Comment by jag3773** [comment]
Yes.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by greenpotatochip** [comment]
Fixed with commit d65da6
this issue can be closed
