### ISSUE TITLE
Allow any email to join easily

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#2]
We need to setup a form that allows any email address to join our channels.  Something like this: https://levels.io/slack-typeform-auto-invite-sign-ups/.

Simple form that asks for name and email, then it should post to our Slack team to send that email address an invite.

**Comment by yvonnel098** [comment]
What should the user submit other than name and email address?

Is there any verification I should do (blocking certain domain...etc)?

Should the form and subsequent processing be hosted on door43 as part of dokuwiki?

Does the user needs to first login to dokuwiki?

**Comment by jag3773** [comment]
First and last name and email are all that is needed. The form should be on Door43 but the user does not have to be logged in.
