### ISSUE TITLE
Setup vhost for Logging

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#27]
We need to host the logs (from #3 ) on a virtual host, possibly team.door43.org.  This should be proxied through Nginx as well.

**Comment by jag3773** [comment]
The logging service is listening on 8081, so let's setup an nginx config that proxies that to team.door43.org.  Some Nginx examples are in the puppet repo, @kuttaineh .

**Comment by kuttaineh** [comment]
Found example http://wiki.nginx.org/ServerBlockExample

**Comment by greenpotatochip** [comment]
Added proxy config to puppet w/commit 47e431d6b
https://team.door43.org:8081/ => http://mon.door43.org:8081/

**Comment by jag3773** [comment]
OK, couple changes needed here:
- [x] The main site needs to be listening on the normal SSL port of 443.
- [x] The main site needs to be on the mon server.
- [x] Once the above are setup, have me change DNS for team.door43.org to point at the mon server.
