### ISSUE TITLE
Update Bot Logging Message

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#29]
When logging is enabled the bot says, "I'm logging messages in resources at http://mon.door43.org:8081/logs/resources/20150813", would be better if the URL was simply http://mon.door43.org:8081/logs/resources/.  That way it's easier for people to see previous days.

**Comment by superdav42** [comment]
@jag3773 with #32 this won't be shown at all. Do you want it to be?
Might make the most sense to add it to the "about this channel" or "pinned items" so anyone could find a link to the longs there. We'd have to manually add it for each channel though.

**Comment by jag3773** [comment]
If we can make a new log option so that a user can ask `bot where are the logs` and the bot replies with http://mon.door43.org:8081/logs/random/ , as an example, that would be great.  The URL base (http://mon.door43.org:8081/logs/) should be an environment variable and then the channel name can be dynamically loaded by the bot in constructing the response.

Will that work?
