### ISSUE TITLE
History and Search plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#3]
We need a hubot plugin (maybe 'history') that can record everything and then provide a search feature to access the historical information.

**Comment by jag3773** [comment]
Log should include the channel and the message.  See https://github.com/github/hubot-scripts/blob/master/src/scripts/history.coffee as an example.

**Comment by jag3773** [comment]
Yvonne, have you had any traction on this?

**Comment by yvonnel098** [comment]
I installed hubot.  The hubot shell comes on but it is not responding to any commands other than the very basic ones (help, exit).  I'm currently working on the dokuwiki editor preference plugin.  Should I concentrate on this instead?

**Comment by jag3773** [comment]
OK, please prioritize the DW editor one over this.  I'll assign this to another dev.

**Comment by superdav42** [comment]
Found https://github.com/adragomir/hubot-logger which might be useful to use, I'll see if I can get it running. also https://github.com/anarcher/hubot-simple-logger and https://github.com/jenrzzz/hubot-logger

**Comment by jag3773** [comment]
Fix usernames in logs.  See PM for link.

**Comment by jag3773** [comment]
Also, set it up to auto log all public channels.

**Comment by jag3773** [comment]
Where are we at on the username issue @superdav42 ?

**Comment by superdav42** [comment]
@jag3773 https://github.com/unfoldingWord-dev/hubot/pull/26

**Comment by jag3773** [comment]
I'm not sure that the logging by default is working.... Username issue is fixed, thanks!

**Comment by jag3773** [comment]
@superdav42 We need an index page that lists and links to all the channels by their slack name, e.g.

```
#general
#random
```

Those should link to the respective page for each channel, e.g. logs/random.

**Comment by jag3773** [comment]
Prevent bot from automatically logging in private channels (even if the bot is in the channel).

**Comment by superdav42** [comment]
last 2 issues fixed by https://github.com/unfoldingWord-dev/hubot/pull/33

**Comment by jag3773** [comment]
The room list does not appear to be working.

**Comment by jag3773** [comment]
great, working now!
