### ISSUE TITLE
RT Link Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#4]
In the Help Desk channel the pattern #[0-9]+ should turn into a link to the ticket, which would be https://help.door43.org/Ticket/Display.html?id=NUMBER.

e.g entering #11 would become https://help.door43.org/Ticket/Display.html?id=11

**Comment by simis** [comment]
Make sure to add Travis-CI yml file from https://github.com/github/hubot/blob/master/.travis.yml to get Travis-CI to do a build test of the hubot changes
