### ISSUE TITLE
RT New Ticket Plugin

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#5]
When a new ticket arrives in the Help Desk we need to put a link to it in the Help Desk channel.  Ideally we can include the subject line.

**Comment by simis** [comment]
How do we know when a ticket has arrived at the help desk?

**Comment by simis** [comment]
Cron Patterns -> http://help.sap.com/saphelp_xmii120/helpdata/en/44/89a17188cc6fb5e10000000a155369/content.htm

**Comment by simis** [comment]
Automation and Monitoring with Hubot -> https://leanpub.com/automation-and-monitoring-with-hubot/read

**Comment by simis** [comment]
Using time zone 'America/Chicago' for CST

**Comment by simis** [comment]
Excluding the time zone information because the task of checking every hour is time zone independent

**Comment by simis** [comment]
request tracker rest api wiki - http://requesttracker.wikia.com/wiki/REST

**Comment by simis** [comment]
Helpful in understanding query for RT rest API - https://wiki.egi.eu/wiki/RT_Help

**Comment by simis** [comment]
Hubot Documentation starts here -> https://hubot.github.com/docs/

**Comment by simis** [comment]
CoffeeScript sample hubot RT script - https://github.com/jtslear/hubot-request-tracker/blob/master/request_tracker.coffee

**Comment by simis** [comment]
Dokuwiki cookie - https://github.com/unfoldingWord-dev/Door43/blob/development/lib/plugins/translation/script.js
