### ISSUE TITLE
Read tD Language Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/hubot#8]
We need to proces http://td.unfoldingword.org/exports/langnames.json and provide information about languages.

Someone may need to know the language code for French, so querying 'td french' should return the top 3 possible language codes, with links to their respective tD pages (e.g. http://td.unfoldingword.org/uw/languages/1868/).

**Comment by jag3773** [comment]
Probably need a query to list the gateway languages as well.  Querying for a language code (e.g. 'td gad') should return the name of the language, it's Gateway Language, and link to it's tD page.

**Comment by superdav42** [comment]
@jag3773 PR made https://github.com/unfoldingWord-dev/hubot/issues/34

**Comment by jag3773** [comment]
Does not appear to work.
